# CMake generated Testfile for 
# Source directory: /home/jgh/Documentos/pulsar_installer/src/modules/partition/tests
# Build directory: /home/jgh/Documentos/pulsar_installer/build_new/src/modules/partition/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(partitionjobtest "/home/jgh/Documentos/pulsar_installer/build_new/partitionjobtest")
set_tests_properties(partitionjobtest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/modules/partition/tests/CMakeLists.txt;23;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/modules/partition/tests/CMakeLists.txt;0;")
add_test(partitionclearmountsjobtest "/home/jgh/Documentos/pulsar_installer/build_new/partitionclearmountsjobtest")
set_tests_properties(partitionclearmountsjobtest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/modules/partition/tests/CMakeLists.txt;38;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/modules/partition/tests/CMakeLists.txt;0;")
add_test(partitioncreatelayoutstest "/home/jgh/Documentos/pulsar_installer/build_new/partitioncreatelayoutstest")
set_tests_properties(partitioncreatelayoutstest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/modules/partition/tests/CMakeLists.txt;45;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/modules/partition/tests/CMakeLists.txt;0;")
add_test(partitionautomounttest "/home/jgh/Documentos/pulsar_installer/build_new/partitionautomounttest")
set_tests_properties(partitionautomounttest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/modules/partition/tests/CMakeLists.txt;57;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/modules/partition/tests/CMakeLists.txt;0;")
add_test(partitiondevicestest "/home/jgh/Documentos/pulsar_installer/build_new/partitiondevicestest")
set_tests_properties(partitiondevicestest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/modules/partition/tests/CMakeLists.txt;63;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/modules/partition/tests/CMakeLists.txt;0;")
add_test(partitionconfigtest "/home/jgh/Documentos/pulsar_installer/build_new/partitionconfigtest")
set_tests_properties(partitionconfigtest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/modules/partition/tests/CMakeLists.txt;70;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/modules/partition/tests/CMakeLists.txt;0;")
