# CMake generated Testfile for 
# Source directory: /home/jgh/Documentos/pulsar_installer/src/libcalamares
# Build directory: /home/jgh/Documentos/pulsar_installer/build_new/src/libcalamares
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(libcalamarestest "/home/jgh/Documentos/pulsar_installer/build_new/libcalamarestest")
set_tests_properties(libcalamarestest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;221;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresgeoiptest "/home/jgh/Documentos/pulsar_installer/build_new/libcalamaresgeoiptest")
set_tests_properties(libcalamaresgeoiptest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;223;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamareslocaletest "/home/jgh/Documentos/pulsar_installer/build_new/libcalamareslocaletest")
set_tests_properties(libcalamareslocaletest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;225;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresmodulesystemtest "/home/jgh/Documentos/pulsar_installer/build_new/libcalamaresmodulesystemtest")
set_tests_properties(libcalamaresmodulesystemtest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;227;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresnetworktest "/home/jgh/Documentos/pulsar_installer/build_new/libcalamaresnetworktest")
set_tests_properties(libcalamaresnetworktest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;229;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamarespackagestest "/home/jgh/Documentos/pulsar_installer/build_new/libcalamarespackagestest")
set_tests_properties(libcalamarespackagestest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;231;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamarespartitiontest "/home/jgh/Documentos/pulsar_installer/build_new/libcalamarespartitiontest")
set_tests_properties(libcalamarespartitiontest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;234;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamarespartitionkpmtest "/home/jgh/Documentos/pulsar_installer/build_new/libcalamarespartitionkpmtest")
set_tests_properties(libcalamarespartitionkpmtest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;239;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresutilstest "/home/jgh/Documentos/pulsar_installer/build_new/libcalamaresutilstest")
set_tests_properties(libcalamaresutilstest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;242;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresutilspathstest "/home/jgh/Documentos/pulsar_installer/build_new/libcalamaresutilspathstest")
set_tests_properties(libcalamaresutilspathstest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/jgh/Documentos/pulsar_installer/build_new:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/jgh/Documentos/pulsar_installer/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;244;calamares_add_test;/home/jgh/Documentos/pulsar_installer/src/libcalamares/CMakeLists.txt;0;")
