# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_DEB "ON")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BUILD_SOURCE_DIRS "/home/jgh/Documentos/pulsar_installer;/home/jgh/Documentos/pulsar_installer/build_new")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.25/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "CALAMARES built using CMake")
set(CPACK_GENERATOR "STGZ;TGZ;TZ;DEB")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/jgh/Documentos/pulsar_installer/build_new;CALAMARES;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr")
set(CPACK_MODULE_PATH "/usr/share/ECM/modules/;/usr/share/ECM/find-modules/;/usr/share/ECM/kde-modules/;/home/jgh/Documentos/pulsar_installer/CMakeModules")
set(CPACK_NSIS_DISPLAY_NAME "CALAMARES 3.3.15")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "CALAMARES 3.3.15")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/jgh/Documentos/pulsar_installer/build_new/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "Calamares is a Linux system installer, intended for Linux distributions to use on their ISOs and other bootable media to install the distribution to the end-user's computer. Calamares can also be used as an OEM configuration tool. It is modular, extensible and highly-configurable for Linux distributions from all five major Linux families.")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.25/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A Linux system installer")
set(CPACK_PACKAGE_FILE_NAME "CALAMARES-3.3.15-Linux")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://calamares.io/")
set(CPACK_PACKAGE_ICON "data/images/squid.png")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "CALAMARES 3.3.15")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "CALAMARES 3.3.15")
set(CPACK_PACKAGE_NAME "CALAMARES")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "calamares")
set(CPACK_PACKAGE_VERSION "3.3.15")
set(CPACK_PACKAGE_VERSION_MAJOR "3")
set(CPACK_PACKAGE_VERSION_MINOR "3")
set(CPACK_PACKAGE_VERSION_PATCH "15")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake-3.25/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.25/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.25/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/jgh/Documentos/pulsar_installer/build_new/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/jgh/Documentos/pulsar_installer/build_new/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()

# DEB-specific configuration
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "calamares")
set(CPACK_DEBIAN_PACKAGE_SECTION "admin")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6, libgcc-s1, libqt5core5a, libqt5gui5, libqt5widgets5, libqt5dbus5, libqt5network5, libqt5svg5, libqt5qml5, libqt5quick5, libqt5quickwidgets5, libkf5coreaddons5, libkf5crash5, libkf5parts5, libkf5service5, libkf5solid5, libkf5dbusaddons5, libkf5widgetsaddons5, libkf5package5, libkf5iconthemes5, libkf5i18n5, libkf5config-core5, libkf5configwidgets5, libkf5auth5, libkf5xmlgui5, libkf5kiocore5, libkf5kiogui5, libkf5kiowidgets5, libkf5kiofilewidgets5, libkf5itemviews5, libkf5completion5, libkf5guiaddons5, libkf5jobwidgets5, libkf5codecs5, libkf5windowsystem5, libkf5archive5, parted, kpartx, e2fsprogs, dosfstools, jfsutils, ntfs-3g, xfsprogs, hfsutils, hfsprogs, f2fs-tools, nilfs-tools, udftools, dmsetup, mdadm, lvm2, cryptsetup")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "")
